version: '3'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper-1
    container_name: zookeeper-1
    volumes:
      - ./kafka/zookeeper-1_data:/var/lib/zookeeper/data
      - ./kafka/zookeeper-1_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
    networks:
      - ai-orchestra-network

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper-2
    container_name: zookeeper-2
    volumes:
      - ./kafka/zookeeper-2_data:/var/lib/zookeeper/data
      - ./kafka/zookeeper-2_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
    networks:
      - ai-orchestra-network

  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper-3
    container_name: zookeeper-3
    volumes:
      - ./kafka/zookeeper-3_data:/var/lib/zookeeper/data
      - ./kafka/zookeeper-3_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
    networks:
      - ai-orchestra-network

  broker-1:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker-1
    container_name: broker-1
    volumes:
      - ./kafka/broker-1-data:/var/lib/kafka/data
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,INTERNAL://broker-1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SNAPSHOT_TRUST_EMPTY: true
    networks:
      - ai-orchestra-network

  broker-2:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker-2
    container_name: broker-2
    volumes:
      - ./kafka/broker-2-data:/var/lib/kafka/data
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - broker-1
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9093,INTERNAL://broker-2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SNAPSHOT_TRUST_EMPTY: true
    networks:
      - ai-orchestra-network

  broker-3:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker-3
    container_name: broker-3
    volumes:
      - ./kafka/broker-3-data:/var/lib/kafka/data
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - broker-1
      - broker-2
    ports:
      - 9094:9094
      - 29094:29094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9094,INTERNAL://broker-3:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SNAPSHOT_TRUST_EMPTY: true
    networks:
      - ai-orchestra-network

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    image: ai-orchestra/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8082:8082"
      - "8083:8083"
    environment:
      ASPNETCORE_HTTPS_PORT: "https://+:8083"
      ASPNETCORE_URLS: "http://+:8082"
    networks:
      - ai-orchestra-network

networks:
  ai-orchestra-network:
    driver: bridge